In [77]:
import json
with open('00BASICS-ANSWERS.json') as f:
    data = json.load(f)
answer = data['0']

print("What is NumPy's main object?")
    

What is NumPy's main object?


In [78]:
print(answer)

homogenous multidimensional array


In [79]:
print(f"What is a {answer}?")
answer = data['1']

What is a homogenous multidimensional array?


In [80]:
print(answer)

table of elements, all of the same type, indexed by a tuple of non-negative integers


In [81]:
print("What are dimensions called in numpy?")
answer = data['2']

What are dimensions called in numpy?


In [82]:
answer

'axes'

In [83]:
import numpy as np
from random import randint

arr1 = np.array([randint(1,10) for _ in range(5)])
print("Don't know why they call it axes if they use .ndim?")
print("""
arr1 = np.array([randint(1,10) for _ in range(5)]) # we've created an array of 5 random digits
print(arr1, arr1.ndim) # now we're displaying the array itself and its axes
""")
print(arr1, arr1.ndim)
print("How would you create an array with more than one axes?")


Don't know why they call it axes if they use .ndim?

arr1 = np.array([randint(1,10) for _ in range(5)]) # we've created an array of 5 random digits
print(arr1, arr1.ndim) # now we're displaying the array itself and its axes

[2 4 4 2 9] 1
How would you create an array with more than one axes?


In [84]:
def getArray(elements):
    return np.array([randint(1,10) for _ in range(elements)])
arr2 = np.array([getArray(5) for _ in range(3)])
print("""
def getArray(elements):
    return np.array([randint(1,10) for _ in range(elements)])
arr2 = np.array([getArray(5) for _ in range(3)])      
""")
print(arr2, arr2.ndim)


def getArray(elements):
    return np.array([randint(1,10) for _ in range(elements)])
arr2 = np.array([getArray(5) for _ in range(3)])      

[[4 1 9 1 2]
 [5 7 1 9 3]
 [7 4 9 9 2]] 2


In [85]:
print("What's the difference between python's and numpy's array class?")

What's the difference between python's and numpy's array class?


In [86]:
answer = data['3']
print(answer)

python's only handles one dimensional arrays, compared to numpy's ndarray


In [87]:
print("What is the shape of arr2?")

What is the shape of arr2?


In [88]:
print(arr2.shape)

(3, 5)


In [89]:
print("What is the size of arr2?")

What is the size of arr2?


In [91]:
print(arr2.size)

15


In [92]:
print("What is the dtype of arr2?")

What is the dtype of arr2?


In [93]:
print(arr2.dtype)

int32


In [94]:
print("What is the item size of arr2?")

What is the item size of arr2?


In [95]:
print(arr2.itemsize)

4


In [96]:
print("Why would we ever use ndarray.data?")
answer = data['4']

Why would we ever use ndarray.data?


In [97]:
print(answer)

dealing with c, accessing the underlying memory buffer, GPU demands
