In [8]:
import numpy as np
arr1 = np.arange(12)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [6]:
import json
with open("02PRINTING-ARRAYS-ANSWERS.json") as f:
    data = json.load(f)
answer = data["0"]
print("How do you change the dimensions of an array?")

How do you change the dimensions of an array?


In [9]:
print(answer)


by reshaping the array


In [11]:
print("""arr2 = arr1.reshape(3, 4)""")
arr2 = arr1.reshape(3, 4)
arr2

arr2 = arr1.reshape(3, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
print("""arr3 = arr2.reshape(3, 2, 2)""")
arr3 = arr2.reshape(3, 2, 2)
arr3

arr3 = arr2.reshape(3, 2, 2)


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])