In [96]:
from random import randint
def getNum():
    return randint(1, 9)

def getRandomList(count):
    return np.array([getNum() for _ in range(count)])

print("Numpy allows you to perform operations on arrays elementwise.")


Numpy allows you to perform operations on arrays elementwise.


In [115]:
import numpy as np
print("Let's subtract a pair!")
arr1 = getRandomList(3)
arr2 = getRandomList(3)
arr3 = arr1 - arr2
print("arr1 - arr2 = arr3")
print(arr1, "-", arr2, "=", arr3)

Let's subtract a pair!
arr1 - arr2 = arr3
[2 6 1] - [7 8 3] = [-5 -2 -2]


In [116]:
print("Let's power each value by 2!")


Let's power each value by 2!


In [117]:
print("arr1 ^ 2 = arr2")
print(arr1, "**", 2, "=", arr1**2)

arr1 ^ 2 = arr2
[2 6 1] ** 2 = [ 4 36  1]


In [118]:
print("Let's take 10 to the power of multiples of e!")

Let's take 10 to the power of multiples of e!


In [119]:
print("Let's multiply 69 by the cosine of every number in an array!")

Let's multiply 69 by the cosine of every number in an array!


In [120]:
print("69 * np.cos(arr1) = arr2")
arr2 = 69 * np.cos(arr1)
print("69 * np.cos(", arr1, ") =", arr2)
print("69 * ", [np.cos(i) for i in arr1], " =", arr2)
print([69 * np.cos(i) for i in arr1], " =", arr2)


69 * np.cos(arr1) = arr2
69 * np.cos( [2 6 1] ) = [-28.71413172  66.25174978  37.2808591 ]
69 *  [-0.4161468365471424, 0.960170286650366, 0.5403023058681398]  = [-28.71413172  66.25174978  37.2808591 ]
[-28.714131721752825, 66.25174977887525, 37.280859104901644]  = [-28.71413172  66.25174978  37.2808591 ]


In [121]:
print("Let's compare to each value!")

Let's compare to each value!


In [122]:
print("arr1 < 6.9 = arr2")
arr2 = arr1 < 6.9
print(arr1, "<",6.9 ,"=", arr2)

arr1 < 6.9 = arr2
[2 6 1] < 6.9 = [ True  True  True]


In [123]:
print("Let's perform matrix multiplication!")
def get2DArr(row, column):
    return np.array([[getNum() for _ in range(column)] for _ in range(row)])
arr1 = get2DArr(2, 2)
arr2 = get2DArr(2, 2)
print("arr1\nx\narr2\n=\narr3\n")
print(arr1, "\nx\n", arr2, "\n=\n", arr1 @ arr2)

Let's perform matrix multiplication!
arr1
x
arr2
=
arr3

[[8 9]
 [4 3]] 
x
 [[1 9]
 [5 1]] 
=
 [[53 81]
 [19 39]]


In [124]:
print("Other than @, what else is available to perform matrix multiplication?")

Other than @, what else is available to perform matrix multiplication?


In [125]:
print("arr1\nx\narr2\n=\narr3\n")
print(arr1, "\nx\n", arr2, "\n=\n", arr1.dot(arr2))

arr1
x
arr2
=
arr3

[[8 9]
 [4 3]] 
x
 [[1 9]
 [5 1]] 
=
 [[53 81]
 [19 39]]


In [126]:
print(".dot")

.dot


In [127]:
print("modifying an existing array rather than create a new one!")

modifying an existing array rather than create a new one!


In [131]:
arr1 = get2DArr(2, 3)
print("arr1 += 1")
print(arr1, "+=", 1)
arr1 += 1
arr1

arr1 += 1
[[1 3 6]
 [7 8 5]] += 1


array([[2, 4, 7],
       [8, 9, 6]])

In [133]:
arr2 = get2DArr(2, 3)
print("arr2 *= 2")
print(arr2, "*=", 2)
arr2 *= 2
arr2

arr2 *= 2
[[9 7 8]
 [6 4 8]] *= 2


array([[18, 14, 16],
       [12,  8, 16]])

In [139]:
print("""getting random with python
from random import randint
num = randint(1, 9)
num
""")
from random import randint
num = randint(1, 9)
num

getting random with python
from random import randint
num = randint(1, 9)
num



2

In [157]:
print("""getting random with numpy
rg = np.random.default_rng(1)
nums = rg.random((2, 2))
nums *= 10 
nums
      """)
rg = np.random.default_rng(1)
nums = rg.random((2, 2))
nums *= 10 
nums


getting random with numpy
rg = np.random.default_rng(1)
nums = rg.random((2, 2))
nums *= 10 
nums
      


array([[5.11821625, 9.50463696],
       [1.44159613, 9.48649447]])

In [169]:
print("but a random numpy matrix doesn't automatically convert to one another")

but a random numpy matrix doesn't automatically convert to one another


In [170]:
print("""
nums_one = np.ones((2, 2), dtype=int)
nums_one
""")
nums_one = np.ones((2, 2), dtype=int)
nums_one


nums_one = np.ones((2, 2), dtype=int)
nums_one



array([[1, 1],
       [1, 1]])

In [173]:
print("""
float += integer
nums += nums_one
nums
""")
nums += nums_one
nums


float += integer
nums += nums_one
nums



array([[12.11821625, 16.50463696],
       [ 8.44159613, 16.48649447]])

In [176]:
print("""
integer += float
nums_one += nums
nums_one""")
nums_one += nums
nums_one


integer += float
nums_one += nums
nums_one


UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [180]:
print("some unary operations methods of the ndarray class")
arr4 = rg.random((2,2))
arr4

some unary operations methods of the ndarray class


array([[0.54959369, 0.02755911],
       [0.75351311, 0.53814331]])

In [181]:
arr4.sum()

1.8688092228102127

In [182]:
arr4.min()

0.027559113243068367

In [183]:
arr4.max()

0.7535131086748066

In [184]:
print("how to apply unary operations methods of the ndarray class along a specified axis of an array?")

how to apply unary operations methods of the ndarray class along a specified axis of an array?


In [186]:
arr5 = arr4 * 10
arr5

array([[5.49593688, 0.27559113],
       [7.53513109, 5.38143313]])

In [188]:
print("column wise")
arr5.sum(axis=0)

column wise


array([13.03106796,  5.65702426])

In [189]:
print("row wise")
arr5.sum(axis=1)

row wise


array([ 5.77152801, 12.91656422])

In [191]:
print("row wise cum sum")
arr5.cumsum(axis=1)

row wise cum sum


array([[ 5.49593688,  5.77152801],
       [ 7.53513109, 12.91656422]])